name: Build

on:
  workflow_call:
  push:
  pull_request:
    branches:
      - master

env:
  CONFIGURE_PRESET: default-release

jobs:
  build:
    strategy:
      matrix:
        api-version:
          - ref: e1542ed05f3f8c273206bb9ead8d39fea87430bb
            abi: 49
          - ref: dev
            abi: 51
        platform:
          - name: ubuntu
            binary-path: build/
            binary: libbinja-msvc.so
          - name: windows
            binary_path: build\Debug\
            binary: binja-msvc.dll
          - name: macos
            binary-path: build/
            binary: libbinja-msvc.dylib
    runs-on: ${{matrix.platform.name}}-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Fetch binaryninja-api
      uses: actions/checkout@v4
      with:
        repository: Vector35/binaryninja-api
        ref: ${{matrix.api-version.ref}}
        path: binaryninja-api
        submodules: recursive
        sparse-checkout: |
          .
          python
          rapidjson
          rust
          cmake
          json
          vendor
          examples

    - name: Apply binaryninja-api patch
      working-directory: binaryninja-api
      run: git apply ../.github/binaryninja-api-headless.patch

    - name: Build
      run: |
        cmake -S . -B build -DHEADLESS=1 -DBN_INSTALL_DIR=binaryninja-api -DBN_API_PATH=binaryninja-api
        cmake --build build
        mv ${{matrix.platform.binary-path}}${{matrix.platform.binary}} ${{matrix.platform.binary-path}}${{matrix.api-version.abi}}-${{matrix.platform.binary}}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: lib-${{matrix.platform.name}}-${{matrix.api-version.abi}}
        path: ${{matrix.platform.binary-path}}${{matrix.api-version.abi}}-${{matrix.platform.binary}}
        if-no-files-found: error
